### ISSUE TITLE
有一个问题

### ISSUE THREAD

**Issue by BlameTwo** [TomyJan/Kuro-API-Collection#4]
他这个怎样分辨那一天是签到了，那一天漏签了，看了两天没看出来

**Comment by TomyJan** [comment]
api只给的是签到天数和漏签天数, 补签不用管是哪天

当然你非要知道的话可以自己取签到记录然后分析

**Comment by BlameTwo** [comment]
歪日，真的就是比对签到日期和签到类型？库洛真傻逼

**Comment by TomyJan** [comment]
因为他的签到逻辑就是累签获取, 而不是日签获取

**Comment by BlameTwo** [comment]
😂那我也不用比对了，如果是累计我直接拿签到天数就算了
