### ISSUE TITLE
求问，有没有角色练度的接口？

### ISSUE THREAD

**Issue by jokingzhang** [TomyJan/Kuro-API-Collection#5]

**Comment by TomyJan** [comment]
有啊， 不过只有基础信息，看不到数值，具体自己库街区看

**Comment by jokingzhang** [comment]
有没有单个角色的接口？
![image](https://github.com/user-attachments/assets/88e67bbe-ffd7-4a69-8f83-8fce8b1a798d)

**Comment by jokingzhang** [comment]
我找到了
